# 站点基本信息
title: My Jekyll Site          # 网站标题
description: >-                # 网站描述
  欢迎来到我的 Jekyll 网站！这里是一个简洁的博客。
baseurl: ""                    # 网站的子路径（例如 /blog），如果部署在根目录，请留空
url: "https://siyuanwang314-prog.github.io"  # 网站的完整URL，替换为你的GitHub Pages链接

# 作者信息
author:
  name: siyuanwang              # 作者名字
  email: siyuanwang314@gmail.com # 作者邮箱

# SEO 配置
permalink: /:categories/:title/  # 页面永久链接格式
markdown: kramdown              # Markdown 渲染引擎
theme: minima                   # 使用的主题（可以替换为其他主题）

# 站点语言和时间
locale: zh-CN                  # 网站语言（中文）
timezone: Asia/Shanghai        # 时区（上海时间）

# 插件配置
plugins:
  - jekyll-feed                # RSS 订阅插件
  - jekyll-seo-tag             # SEO 优化插件
  - jekyll-sitemap             # 自动生成网站地图插件

# 导航菜单
navbar:
  - name: Home
    url: /
  - name: About
    url: /about/
  - name: Blog
    url: /blog/

# 代码高亮
highlighter: rouge             # 代码高亮工具
kramdown:
  input: GFM
  syntax_highlighter: rouge

# 页面构建的额外设置
paginate: 5                    # 每页文章数量
paginate_path: "/page:num/"    # 分页路径格式

# 输出忽略文件/目录
exclude:
  - README.md                  # 忽略 README 文件
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# GitHub Pages 特定配置
github:
  is_project_page: true        # 如果你的项目部署在 GitHub Pages 子路径，需要设置为 true
